# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='ts',
            new_name='timestamp',
        ),
    ]
