# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('trading', '0002_auto_20170919_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to='authentication.Profile'),
            preserve_default=False,
        ),
    ]
