# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('trading', '0003_auto_20170919_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradingaccount',
            unique_together=set([('profile', 'account_name')]),
        ),
    ]
