# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBitcoin', '0004_dailystockquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystockquote',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BuyBitcoin.Stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='trade',
            field=models.ManyToManyField(to='BuyBitcoin.Trade'),
        ),
        migrations.AddField(
            model_name='trade',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BuyBitcoin.TradingAccount'),
            preserve_default=False,
        ),
    ]
