# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 03:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBitcoin', '0006_auto_20170918_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystockquote',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quote', to='BuyBitcoin.Stock'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='BuyBitcoin.TradingAccount'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='BuyBitcoin.Stock'),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
