# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbank',
            name='institution_name',
            field=models.CharField(default='tb', max_length=1000),
            preserve_default=False,
        ),
    ]
