# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masked_id', models.IntegerField()),
                ('Date', models.DateField()),
                ('Des1', models.CharField(max_length=255)),
                ('Des2', models.CharField(max_length=255)),
                ('Des3', models.CharField(max_length=255)),
                ('Payment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masked_id', models.IntegerField()),
                ('Date', models.DateField()),
                ('des1', models.CharField(max_length=255)),
                ('des2', models.CharField(max_length=255)),
                ('des3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DailyWebsiteTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masked_id', models.IntegerField()),
                ('Date', models.DateField()),
                ('wf_page', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MonthEndBalances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masked_id', models.IntegerField()),
                ('asof_yyyymm', models.DateField()),
                ('age', models.IntegerField()),
                ('tenure_altered', models.DecimalField(decimal_places=2, max_digits=16)),
                ('checking_acct', models.IntegerField()),
                ('savings_acct_ct', models.IntegerField()),
                ('mortgage_flag', models.BooleanField()),
                ('heloc_flag', models.BooleanField()),
                ('personal_loan_flag', models.BooleanField()),
                ('cc_flag', models.BooleanField()),
                ('prot_acct_flag', models.BooleanField()),
                ('check_bal_altered', models.DecimalField(decimal_places=2, max_digits=16)),
                ('sav_bal_altered', models.DecimalField(decimal_places=2, max_digits=16)),
                ('mortgage_bal_altered', models.DecimalField(decimal_places=2, max_digits=16)),
                ('heloc_bal_altered', models.DecimalField(decimal_places=2, max_digits=16)),
                ('personal_loan_bal_altered', models.DecimalField(decimal_places=2, max_digits=16)),
                ('atm_withdrawls_cnt', models.IntegerField()),
                ('atm_deposits_cnt', models.IntegerField()),
                ('branch_visit_cnt', models.IntegerField()),
                ('phone_banker_cnt', models.IntegerField()),
                ('mobile_bank_cnt', models.IntegerField()),
                ('online_bank_cnt', models.IntegerField()),
                ('direct_mail_cnt', models.IntegerField()),
                ('direct_email_cnt', models.IntegerField()),
                ('direct_phone_cnt', models.IntegerField()),
            ],
        ),
    ]
