# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyinteractions',
            old_name='des1',
            new_name='Des1',
        ),
        migrations.RenameField(
            model_name='dailyinteractions',
            old_name='des2',
            new_name='Des2',
        ),
        migrations.RenameField(
            model_name='dailyinteractions',
            old_name='des3',
            new_name='Des3',
        ),
    ]
