# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wf', '0002_auto_20170919_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthendbalances',
            old_name='checking_acct',
            new_name='checking_acct_ct',
        ),
    ]
