# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wf', '0003_auto_20170919_1426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthendbalances',
            unique_together=set([('masked_id', 'asof_yyyymm')]),
        ),
    ]
