# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailystockquote',
            unique_together=set([('stock', 'date')]),
        ),
    ]
