# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20170920_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentStockConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.Stock')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to='stocks.Stock')),
            ],
        ),
    ]
