# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_investmentbucket_investmentstockconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentstockconfiguration',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.InvestmentBucket'),
        ),
    ]
