# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20171011_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentBucketDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='investmentbucket',
            name='invest_attributes',
            field=models.ManyToManyField(related_name='bucket', to='stocks.InvestmentBucketDescription'),
        ),
    ]
