# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20171011_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentbucket',
            old_name='invest_attributes',
            new_name='invest_desc',
        ),
    ]
