# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20171011_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentbucketdescription',
            name='is_good',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
