# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20171011_1314'),
        ('stocks', '0008_investmentbucketdescription_is_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentbucket',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned_bucket', to='authentication.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentbucket',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
