# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_investmentbucket_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentbucket',
            old_name='total',
            new_name='available',
        ),
    ]
