# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_auto_20171013_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystockquote',
            name='value',
            field=models.FloatField(),
        ),
    ]
