# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_auto_20171013_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentstockconfiguration',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='investmentstockconfiguration',
            name='start',
            field=models.DateField(default='2017-10-10'),
            preserve_default=False,
        ),
    ]
