# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 15:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20171011_1314'),
        ('stocks', '0015_auto_20171014_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystockquote',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Daily stock quote can not be negative')]),
        ),
        migrations.AlterField(
            model_name='investmentbucket',
            name='available',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='The available money can not be negative.')]),
        ),
        migrations.AlterField(
            model_name='investmentbucket',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1, message='The name should not be empty.')]),
        ),
        migrations.AlterField(
            model_name='investmentstockconfiguration',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='The quantity can not be negative.')]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1, message='The name should not be empty.')]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='The ticker should not be empty.')]),
        ),
        migrations.AlterUniqueTogether(
            name='investmentbucket',
            unique_together=set([('name', 'owner')]),
        ),
        migrations.AlterUniqueTogether(
            name='investmentbucketdescription',
            unique_together=set([('text', 'bucket')]),
        ),
    ]
