# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_auto_20171015_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentbucket',
            name='available',
            field=models.FloatField(),
        ),
    ]
