# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 15:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_auto_20171015_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentbucket',
            name='available',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='The available money can not be negative.')]),
        ),
    ]
