# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_auto_20171015_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentstockconfiguration',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentstockconfiguration',
            name='start',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
